website/auth.py
from flask import Blueprint, flash, request, redirect
from flask import render_template
from flask.helpers import url_for
from .models import *
from .funtion.validator import Validator
from .funtion.user_manager import UserManager
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_required, login_user, logout_user, current_user

validator = Validator()
user = UserManager()
auth = Blueprint("auth", __name__)


@auth.route('/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    else:
        if request.method == "POST":
            email = request.form.get('email')
            password = request.form.get('password')
            user = User.query.filter_by(email=email).first()
            if user:
                if check_password_hash(user.password, password):
                    flash("Welcome to VAS {}".format(user.full_name), category='success')
                    login_user(user, remember=True)
                    return redirect (url_for('views.home'))
                else:
                    flash("Invalid Password", category='error')
                    return redirect(url_for('auth.login'))
            else:
                flash("User not Found", category='error')
            return redirect(url_for('auth.login'))
        else:
            return render_template('login.html')


@auth.route('/logout')
def logout():
    logout_user()
    flash("Good bye and Have a nice day", category='success')
    return redirect(url_for('auth.login'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == "POST":
        fullname = request.form.get('fullname')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        if password1 != password2:
            flash("Password is not Match", category="error")
        
        ## Check the length of Fullname ##    
        elif len(fullname) < 2:
            flash("Fullname must be greater than 2 character", category="error")
        
        ## Call the Validation Password to Validate Password ##    
        elif validator.passwordValidator(password1) == False:
            flash("Weak password. Password must be with 8-15 character and must contain special character", category='error')    
        else:
            ## Call the register function ##
            user.register(fullname, email, password1)
        return redirect(url_for('auth.signup'))
            
    else:
        print(request.url_root)
        return render_template("signup.html")

website/views.py
from flask import Flask, Blueprint, render_template, redirect, flash, request
from sqlalchemy.sql.functions import user
from .funtion.user_manager import UserManager
from .funtion.product_manager import ProductManager
from flask.helpers import url_for
from werkzeug.utils import secure_filename
from .models import *
import os
from flask_login import login_required, current_user

dest_dir = os.path.join('uploads')

views = Blueprint("views", __name__)
users = UserManager()
product = ProductManager()

ALLOWED_EXTENSIONS = {'pdf', 'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@views.route('/home')
@login_required
def home():
    current_page = 'current-page'
    return render_template('home.html', home_current_page=current_page)


@views.route('/profile/', methods=['GET', 'POST'])
@login_required
def profile():
    current_page = 'current-page'
    if request.method == "POST":
        address = request.form.get('address')
        state = request.form.get('state')
        mobile = request.form.get('mobile')
        file = request.files['file']
        if Profile.query.filter_by(user_id=current_user.id).first():
            users.update_profile(state, address, mobile, user_id=current_user.id)
        else:
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join(f'website/static/{dest_dir}', filename))
                users.create_profile(state, address, filename, mobile, user_id=current_user.id)
            else:
                flash("Invalid File Format", category='error')
        return redirect(url_for('views.profile'))
    else:
        return render_template('profile.html', user=current_user, profile_current_page=current_page)


    
@views.route('/products/', methods=['GET', 'POST'])
@login_required
def products():
    current_page = 'current-page'
    all_product = product.display_all_product()
    return render_template('products.html', 
                           product_current_page=current_page,
                           all_product=all_product
                           )



@views.route('/addproducts/', methods=['GET', 'POST'])
def add_products():
    
    ## check the request method and get the form data if the it's POST request ##
    if request.method == "POST":
        product_name = request.form.get('product_name')
        product_category = request.form.get('product_category')
        charges = request.form.get('charges')
        live_endpoint = request.form.get('live_endpoint')
        test_endpoint = request.form.get('test_endpoint')
        
        ## Call the add_product function ##
        product.add_product(product_name, product_category, charges, live_endpoint, test_endpoint)
        return redirect(url_for('views.add_products'))
    else:
        return render_template('addproduct.html')
    
    

@views.route('/add_my_product/<code>', methods=['GET', 'POST'])
def add_my_product(code):
    product.customer_add_product(code)
    return redirect(url_for('views.products'))

website/templates/addproduct.html
<!doctype html>
<html lang="en">
	{% include 'shead.html' %}
	<body>
		{% include 'toast/message.html' %}
		<!-- Page wrapper start -->
		<div class="page-wrapper">
			
			<!-- Sidebar wrapper start -->
			{% include 'sidebar.html' %}
			<!-- Sidebar wrapper end -->

			<!-- *************
				************ Main container start *************
			************* -->
			<div class="main-container">

				<!-- Page header starts -->
				{% include 'header.html' %}
				<!-- Page header ends -->

				<!-- Content wrapper scroll start -->
				<div class="content-wrapper-scroll">

					<!-- Content wrapper start -->
					<div class="content-wrapper">

						<!-- Row start -->
						<div class="row gutters">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

								<!-- Card start -->
								<div class="card">
									<div class="card-header">
										<div class="card-title">Add Products</div>
									</div>
									<div class="card-body">
										
										<!-- Row start -->
										<form method="POST" action="{{url_for('views.add_products')}}">
										<div class="row gutters">
											<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
												
												<!-- Field wrapper start -->
												<div class="field-wrapper">
													<input class="form-control" type="text" name="product_name">
													<div class="field-placeholder">Product Name <span class="text-danger">*</span></div>
													<div class="form-text">
														Please enter product name.
													</div>
												</div>
												<!-- Field wrapper end -->

											</div>
											<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
												
												<!-- Field wrapper start -->
												<div class="field-wrapper">
													<select class="form-control" name="product_category">
														<option value="">Select Product Category</option>
														<option>Electricity</option>
														<option>Mobile Data TopUp</option>
														<option>Mobile Airtime</option>
													</select>
													<div class="field-placeholder">Product Category <span class="text-danger">*</span></div>
													<div class="form-text">
														Please Select Product Category.
													</div>
												</div>
												<!-- Field wrapper end -->

											</div>
											<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
												
												<!-- Field wrapper start -->
												<div class="field-wrapper">
													<input class="form-control" type="text" name="charges">
													<div class="field-placeholder">Charges</div>
													<div class="form-text">
														Please enter product conviniency charge.
													</div>
												</div>
												<!-- Field wrapper end -->

											</div>
											<div class="col-xl-6 col-lg-8 col-md-8 col-sm-8 col-12">
												
												<!-- Field wrapper start -->
												<div class="field-wrapper">
													<input class="form-control" type="text" name="live_endpoint">
													<div class="field-placeholder">Live Endpoint</div>
												</div>
												<!-- Field wrapper end -->

											</div>
											<div class="col-xl-6 col-lg-4 col-md-4 col-sm-4 col-12">
												
												<!-- Field wrapper start -->
												<div class="field-wrapper">
													<input class="form-control" type="text" name="test_endpoint">
													<div class="field-placeholder">Test Endpoint</div>
												</div>
												<!-- Field wrapper end -->

											</div>
											<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
												<button class="btn btn-primary" type="submit">Add Product</button>
											</div>
										</div>
										</form>
										<!-- Row end -->

									</div>
								</div>
								<!-- Card end -->

							</div>
						</div>
						<!-- Row end -->

					</div>
					<!-- Content wrapper end -->

					<!-- App Footer start -->
					{% include 'footer.html' %}
					<!-- App footer end -->

				</div>
				<!-- Content wrapper scroll end -->

			</div>
			<!-- *************
				************ Main container end *************
			************* -->

		</div>
		<!-- Page wrapper end -->

		<!-- *************
			************ Required JavaScript Files *************
		************* -->
		<!-- Required jQuery first, then Bootstrap Bundle JS -->
		{% include 'foot.html' %}

	</body>
</html>

website/templates/foot.html
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
		<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
		<script src="{{ url_for('static', filename='js/modernizr.js') }}"></script>
		<script src="{{ url_for('static', filename='js/moment.js') }}"></script>

		<!-- *************
			************ Vendor Js Files *************
		************* -->
		
		<!-- Megamenu JS -->
		<script src="{{ url_for('static', filename='vendor/megamenu/js/megamenu.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/megamenu/js/custom.js') }}"></script>

		<!-- Slimscroll JS -->
		<script src="{{ url_for('static', filename='vendor/slimscroll/slimscroll.min.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/slimscroll/custom-scrollbar.js') }}"></script>

		<!-- Search Filter JS -->
		<script src="{{ url_for('static', filename='vendor/search-filter/search-filter.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/search-filter/custom-search-filter.js') }}"></script>

		<!-- Apex Charts -->
		<script src="{{ url_for('static', filename='vendor/apex/apexcharts.min.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/apex/custom/home/salesGraph.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/apex/custom/home/ordersGraph.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/apex/custom/home/earningsGraph.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/apex/custom/home/visitorsGraph.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/apex/custom/home/customersGraph.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/apex/custom/home/sparkline.js') }}"></script>

		<!-- Circleful Charts -->
		<script src="{{ url_for('static', filename='vendor/circliful/circliful.min.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/circliful/circliful.custom.js') }}"></script>

		<!-- Main Js Required -->
		<script src="{{ url_for('static', filename='js/main.js') }}"></script>

		<!-- Rating JS -->
		<script src="{{ url_for('static', filename='vendor/rating/raty.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/rating/raty-custom.js') }}"></script>

		<!-- Data Tables -->
		<script src="{{ url_for('static', filename='vendor/datatables/dataTables.min.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap.min.js') }}"></script>
		
		<!-- Custom Data tables -->
		<script src="{{ url_for('static', filename='vendor/datatables/custom/custom-datatables.js') }}"></script>

		<!-- Download / CSV / Copy / Print -->
		<script src="{{ url_for('static', filename='vendor/datatables/buttons.min.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/datatables/jszip.min.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/datatables/pdfmake.min.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/datatables/vfs_fonts.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/datatables/html5.min.js') }}"></script>
		<script src="{{ url_for('static', filename='vendor/datatables/buttons.print.min.js') }}"></script>

website/templates/footer.html
<div class="app-footer">&copy; VAT Service <script>document.write(new Date().getFullYear())</script></div>

website/templates/head.html
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Meta -->
		<meta name="description" content="UniPro App">
		<meta name="author" content="ParkerThemes">
		<link rel="shortcut icon" href="{{ url_for ('static', filename='img/fav.png') }}" />

		<!-- Title -->
		<title>Login Home</title>


		<!-- *************
			************ Common Css Files *************
		************ -->
		<!-- Bootstrap css -->
		<link rel="stylesheet" href="{{ url_for ('static', filename='css/bootstrap.min.css') }}">
		
		<!-- Main css -->
		<link rel="stylesheet" href="{{ url_for ('static', filename='css/main.css') }}">


		<!-- *************
			************ Vendor Css Files *************
		************ -->

	</head>

website/templates/header.html
<div class="page-header">
					
					<!-- Row start -->
					<div class="row gutters">
						<div class="col-xl-8 col-lg-8 col-md-8 col-sm-6 col-9">

							<!-- Search container start -->
							<div class="search-container">

								<!-- Toggle sidebar start -->
								<div class="toggle-sidebar" id="toggle-sidebar">
									<i class="icon-menu"></i>
								</div>
								<!-- Toggle sidebar end -->

								<!-- Mega Menu Start -->
								
								<!-- Mega Menu End -->

								<!-- Search input group start -->
								<div class="ui fluid category search">
									<div class="ui icon input">
										<input class="prompt" type="text" placeholder="Search">
										<i class="search icon icon-search1"></i>
									</div>
									<div class="results"></div>
								</div>
								<!-- Search input group end -->

							</div>
							<!-- Search container end -->

						</div>
						<div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-3">

							<!-- Header actions start -->
							<ul class="header-actions">
								<li class="dropdown">
									<a href="#" id="userSettings" class="user-settings" data-toggle="dropdown" aria-haspopup="true">
										<span class="avatar">
											<img src="{{ url_for('static', filename='img/user.svg') }}" alt="User Avatar">
											<span class="status busy"></span>
										</span>
									</a>
									<div class="dropdown-menu dropdown-menu-end md" aria-labelledby="userSettings">
										<div class="header-profile-actions">
											<a href="{{url_for('views.profile')}}"><i class="icon-user1"></i>Profile</a>
											<a href="#"><i class="icon-settings1"></i>Settings</a>
											<a href="{{url_for('auth.logout')}}"><i class="icon-log-out1"></i>Logout</a>
										</div>
									</div>
								</li>
							</ul>
							<!-- Header actions end -->

						</div>
					</div>
					<!-- Row end -->					

				</div>

website/templates/login.html
<!doctype html>
<html lang="en">
	{% include 'head.html' %}
	<body class="authentication">
		{% include 'toast/message.html' %}
		<!-- Loading wrapper start -->
		<div id="loading-wrapper">
			<div class="spinner-border"></div>
			Loading...
		</div>
		<!-- Loading wrapper end -->

		<!-- *************
			************ Login container start *************
		************* -->
		<div class="login-container">

			<div class="container-fluid h-100">

			<!-- Row start -->
			<div class="row g-0 h-100">
				<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
					<div class="login-about">
						<div class="slogan">
							<span>Design</span>
							<span>Made</span>
							<span>Simple.</span>
						</div>
						<div class="about-desc">
							UniPro a data dashboard is an information management tool that visually tracks, analyzes and displays key performance indicators (KPI), metrics and key data points to monitor the health of a business, department or specific process.
						</div>
						<a href="#" class="know-more">Know More <img src="{{ url_for ('static', filename='img/right-arrow.svg') }}" alt="Uni Pro Admin"></a>

					</div>
				</div>
				<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
					<div class="login-wrapper">
						<form action="{{url_for('auth.login')}}" method="POST">
							<div class="login-screen">
								<div class="login-body">
									<a href="{{url_for('auth.login')}}" class="login-logo">
										<img src="{{ url_for ('static', filename='img/logo.svg') }}" alt="iChat">
									</a>
									<h6>Welcome back,<br>Please login to your account.</h6>
									<div class="field-wrapper">
										<input type="email" name="email" placeholder="Enter Your Email" autofocus>
										<div class="field-placeholder">Email ID</div>
									</div>
									<div class="field-wrapper mb-3">
										<input type="password" name="password" placeholder="Enter Your Password">
										<div class="field-placeholder">Password</div>
									</div>
									<div class="actions">
										<a href="forgot-password.html">Forgot password?</a>
										<button type="submit" class="btn btn-primary">Login</button>
									</div>
								</div>
								<div class="login-footer">
									<span class="additional-link">No Account? <a href="{{ url_for('auth.signup') }}" class="btn btn-light">Sign Up</a></span>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- Row end -->
		
			</div>
		</div>
		<!-- *************
			************ Login container end *************
		************* -->

		<!-- *************
			************ Required JavaScript Files *************
		************* -->
		<!-- Required jQuery first, then Bootstrap Bundle JS -->
		<script src="{{ url_for ('static', filename='js/jquery.min.js') }}"></script>
		<script src="{{ url_for ('static', filename='js/bootstrap.bundle.min.js') }}"></script>
		<script src="{{ url_for ('static', filename='js/modernizr.js') }}"></script>
		<script src="{{ url_for ('static', filename='js/moment.js') }}"></script>
		
		<!-- *************
			************ Vendor Js Files *************
		************* -->

		<!-- Main Js Required -->
		<script src="{{ url_for ('static', filename='js/main.js') }}"></script>

	</body>
</html>

website/templates/products.html
<!doctype html>
<html lang="en">
	{% include 'shead.html' %}
	<body>
		{% include 'toast/message.html' %}
		<!-- Loading wrapper start -->
		<div id="loading-wrapper">
			<div class="spinner-border"></div>
			Loading...
		</div>
		<!-- Loading wrapper end -->

		<!-- Page wrapper start -->
		<div class="page-wrapper">
			
			<!-- Sidebar wrapper start -->
			{% include 'sidebar.html' %}
			<!-- Sidebar wrapper end -->

			<!-- *************
				************ Main container start *************
			************* -->
			<div class="main-container">

				<!-- Page header starts -->
				{% include 'header.html' %}
				<!-- Page header ends -->

				<!-- Content wrapper scroll start -->
				<div class="content-wrapper-scroll">

					<!-- Content wrapper start -->
					<div class="content-wrapper">

						<!-- Row start -->
						<div class="row gutters">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
								
								<div class="card">
									<div class="card-body">
										
										<div class="table-responsive">
											<table id="copy-print-csv" class="table v-middle">
												<thead>
													<tr>
													  <th>Products Name</th>
													  <th>Category</th>													  
													  <th>Added Date</th>													  
													  <th>Charges</th>
													  <th>Status</th>
													  <th>Actions</th>
													</tr>
												</thead>
												<tbody>
												{% for product in all_product %}
													<tr>
													  <td>
													  	<div class="media-box">
													  		<div class="media-box-body">
													  			<a href="#" class="text-truncate">{{product.product_name}}</a>
													  			<p>CODE: #{{product.product_code}}</p>
													  		</div>
													  	</div>
													  </td>
													  <td>
													  	{{product.product_category}}
													  </td>													  
													  <td>{{product.date_added}}</td>
													  <td>₦ {{product.charges }}</td>
													  <td>
													  	{% if product.is_active == true %}
													  		<span class="badge bg-success">Active</span>
														{% else %}
															<span class="badge bg-danger">Not Active</span>
														{% endif %}
													  </td>
													  <td>
													  	<div class="actions">
													  		<a href="{{url_for('views.add_my_product', code=product.product_code)}}"><button type="button" class="btn btn-success">Add</button></a>
													  	</div>
													  </td>
													</tr>
												{% endfor %}
												</tbody>
								    	</table>
										</div>

									</div>
								</div>

							</div>
						</div>
						<!-- Row end -->

					</div>
					<!-- Content wrapper end -->

					<!-- App footer start -->
					{% include 'footer.html' %}
					<!-- App footer end -->

				</div>
				<!-- Content wrapper scroll end -->

			</div>
			<!-- *************
				************ Main container end *************
			************* -->

		</div>
		<!-- Page wrapper end -->

		<!-- *************
			************ Required JavaScript Files *************
		************* -->
		<!-- Required jQuery first, then Bootstrap Bundle JS -->
		{% include 'foot.html' %}

	</body>
</html>

website/templates/profile.html
<!doctype html>
	<html lang="en">
	{% include 'shead.html' %}
	<body>
		{% include 'toast/message.html' %}
		<!-- Loading wrapper start -->
		<div id="loading-wrapper">
			<div class="spinner-border"></div>
			Loading...
		</div>
		<!-- Loading wrapper end -->
		
		<!-- Page wrapper start -->
		<div class="page-wrapper">
			
			<!-- Sidebar wrapper start -->
			{% include 'sidebar.html' %}
			<!-- Sidebar wrapper end -->

			<!-- *************
				************ Main container start *************
				************* -->
				<div class="main-container">

					<!-- Page header starts -->
					{% include 'header.html' %}
					<!-- Page header ends -->

					<!-- Content wrapper scroll start -->
					<div class="content-wrapper-scroll">

						<!-- Content wrapper start -->
						<div class="content-wrapper">

							<!-- Row start -->
							<div class="row gutters">
								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

									<div class="profile-header">
										<h1>Welcome, {{user.full_name}}!!</h1>
										<div class="profile-header-content">
											<div class="profile-header-tiles">
												<div class="row gutters">
													<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
														<div class="profile-tile">
															<span class="icon">
																<i class="icon-server"></i>
															</span>
															<h6>Name - <span>{{user.full_name}}</span></h6>
														</div>
													</div>
													<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
														<div class="profile-tile">
															<span class="icon">
																<i class="icon-map-pin"></i>
															</span>
															<h6>Location - <span>{{user.profile.address}}</span></h6>
														</div>
													</div>
													<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
														<div class="profile-tile">
															<span class="icon">
																<i class="icon-phone1"></i>
															</span>
															<h6>Phone - <span>{{user.profile.mobile}}</span></h6>
														</div>
													</div>
												</div>
											</div>
											<div class="profile-avatar-tile">
												<img src="{{url_for('static', filename='uploads/') }}{{user.profile.image64}}" class="img-fluid" alt="User Profile" />
											</div>
										</div>
									</div>

								</div>
							</div>
							<!-- Row end -->
							
							<!-- Row start -->
							<div class="row gutters">
								<div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">
									<!-- Row start -->
									<form action="{{url_for('views.profile')}}" enctype="multipart/form-data" method="post">
									<div class="accordion-body">
										<div class="field-wrapper">
											<input type="text" {% if user.profile.address == None %} placeholder="Enter Address" {% else %} value="{{user.profile.address}}" {% endif %} name="address" />
											<div class="field-placeholder">Address</div>
										</div>

										<div class="field-wrapper">
											<select name="state">
												<option>Select State</option>
												<option>Ondo</option>
												<option>Lagos</option>
											</select>
											<div class="field-placeholder">State</div>
										</div>

										<div class="field-wrapper">
											<input type="text" name="mobile" {% if user.profile.mobile == None %} placeholder="Enter Mobile Number" {% else %} value="{{user.profile.mobile}}" {% endif %} />
											<div class="field-placeholder">Mobile Number</div>
										</div>
										<div class="field-wrapper">
											<input type="file" name="file" />
											<div class="field-placeholder">Upload Image</div>
										</div>
										<div class="field-wrapper m-0">
											<button class="btn btn-primary stripes-btn">Save</button>
										</div>
									</div>
									</form>
									<!-- Row end -->
								</div>
								<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
									<!-- Row start -->
									<div class="row gutters">
										<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
											<!-- Card start -->
											<div class="stats-tile4 min-height">                                            
												<div class="stats-icon4">
													<i class="icon-receipt"></i>
												</div>
												<h3>2</h3>
												<h4>Certifications</h4>
											</div>
											<!-- Card end -->
										</div>
										<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
											<!-- Card start -->
											<div class="stats-tile4 min-height">                                            
												<div class="stats-icon4">
													<i class="icon-stars"></i>
												</div>
												<h3>7</h3>
												<h4>Awards</h4>
											</div>
											<!-- Card end -->
										</div>
										
									</div>
									<!-- Row end -->                                
								</div>
							</div>
							<!-- Row end -->

						</div>
						<!-- Content wrapper end -->

						<!-- App Footer start -->
						{% include 'footer.html' %}
						<!-- App footer end -->

					</div>
					<!-- Content wrapper scroll end -->

				</div>
			<!-- *************
				************ Main container end *************
				************* -->

			</div>
			<!-- Page wrapper end -->

		<!-- *************
			************ Required JavaScript Files *************
			************* -->
			<!-- Required jQuery first, then Bootstrap Bundle JS -->
			{% include 'foot.html' %}

		</body>
		</html>

website/templates/shead.html
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Meta -->
		<meta name="description" content="Responsive Bootstrap4 Dashboard Template">
		<meta name="author" content="ParkerThemes">
		<link rel="shortcut icon" href="{{ url_for('static', filename='img/fav.png') }}">

		<!-- Title -->
		<title>Uni Pro Admin Template - Admin Dashboard</title>


		<!-- *************
			************ Common Css Files *************
		************ -->
		<!-- Bootstrap css -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
		
		<!-- Icomoon Font Icons css -->
		<link rel="stylesheet" href="{{ url_for('static', filename='fonts/style.css') }}">

		<!-- Main css -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">


		<!-- *************
			************ Vendor Css Files *************
		************ -->

		<!-- Mega Menu -->
		<link rel="stylesheet" href="{{ url_for('static', filename='vendor/megamenu/css/megamenu.css') }}">

		<!-- Search Filter JS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='vendor/search-filter/search-filter.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='vendor/search-filter/custom-search-filter.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='vendor/datatables/dataTables.bs4.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='vendor/datatables/dataTables.bs4-custom.css') }}" />
		<link href="{{ url_for('static', filename='vendor/datatables/buttons.bs.css') }}" rel="stylesheet" />
		
	</head>